<script>
  import { onMount } from 'svelte';
  import AIChatInterface from './AIChatInterface.svelte';

  export let fhirResources;
  export let ipsText;

  let selectedOption = 'app';

  function handleOptionChange(option) {
    selectedOption = option;
  }

  // ... existing code (if any) ...
</script>

<div class="ai-chat-history">
  <div class="option-buttons">
    <button
      on:click={() => handleOptionChange('app')}
      class:selected={selectedOption === 'app'}
    >
      Display app's interpretation of resources
    </button>
    <button
      on:click={() => handleOptionChange('ips')}
      class:selected={selectedOption === 'ips'}
    >
      Display text generated by IPS source
    </button>
    <button
      on:click={() => handleOptionChange('ai-chat')}
      class:selected={selectedOption === 'ai-chat'}
    >
      Chat with AI about your health
    </button>
  </div>

  {#if selectedOption === 'app'}
    <!-- Existing app interpretation display -->
    <div class="app-interpretation">
      <!-- Your existing code for displaying app's interpretation -->
    </div>
  {:else if selectedOption === 'ips'}
    <!-- Existing IPS text display -->
    <div class="ips-text">
      {ipsText}
    </div>
  {:else if selectedOption === 'ai-chat'}
    <AIChatInterface {fhirResources} />
  {/if}
</div>

<style>
  .ai-chat-history {
    /* Your existing styles */
  }
  .option-buttons {
    display: flex;
    justify-content: space-between;
    margin-bottom: 1rem;
  }
  .option-buttons button {
    padding: 0.5rem 1rem;
    border: 1px solid #ccc;
    background-color: #f8f8f8;
    cursor: pointer;
  }
  .option-buttons button.selected {
    background-color: #007bff;
    color: white;
  }
  /* Add any additional styles you need */
</style>
