/**
 * Surfacing AI provenance as an "AI Data Consumer", per the HL7 AI Transparency
 * on FHIR IG (http://hl7.org/fhir/uv/aitransparency).
 *
 * The IG labels AI involvement in several complementary ways, and a consumer has
 * to look at all of them because producers are free to use whichever fit:
 *
 *   Resource level
 *     - Resource.meta.security = v3-ObservationValue#AIAST
 *     - An AI Provenance whose target references the resource with no targetPath
 *     - The AIconfidence extension on the resource root
 *     - The resource pointing at an AI Device (e.g. Observation.device)
 *
 *   Element level
 *     - An AI Provenance target carrying the standard targetPath extension,
 *       e.g. target.extension[targetPath].valueString = "Procedure.followUp.text"
 *     - The AIconfidence extension on a nested element (including as a primitive
 *       extension, e.g. followUp._text.extension)
 *
 * The degree of involvement comes from Provenance.agent.type for the agents that
 * are AI Devices; whether a human reviewed the result comes from the agents that
 * are people. Model-Cards are found on the AI Device (modelCardDescription
 * extension or Device.note.text) or as a Provenance.entity DocumentReference.
 */

import type {
  Annotation,
  Attachment,
  BundleEntry,
  CodeableConcept,
  Device,
  DocumentReference,
  Extension,
  Provenance,
  ProvenanceAgent,
  Reference,
  Resource
} from 'fhir/r4';

const AI_TRANSPARENCY_BASE = 'http://hl7.org/fhir/uv/aitransparency';

export const AI_PROVENANCE_PROFILE = `${AI_TRANSPARENCY_BASE}/StructureDefinition/AI-Provenance`;
export const AI_DEVICE_PROFILE = `${AI_TRANSPARENCY_BASE}/StructureDefinition/AI-Device`;
export const AI_MODEL_CARD_PROFILE = `${AI_TRANSPARENCY_BASE}/StructureDefinition/AI-ModelCard`;
export const AI_INPUT_PROMPT_PROFILE = `${AI_TRANSPARENCY_BASE}/StructureDefinition/AI-InputPrompt`;
export const AI_CONFIDENCE_EXTENSION = `${AI_TRANSPARENCY_BASE}/StructureDefinition/AIconfidence`;
export const AI_KIND_EXTENSION = `${AI_TRANSPARENCY_BASE}/StructureDefinition/aitransparency.AIKind`;
export const MODEL_CARD_EXTENSION = `${AI_TRANSPARENCY_BASE}/StructureDefinition/aitransparency.modelCardDescription`;
export const AI_DEVICE_TYPE_CS = `${AI_TRANSPARENCY_BASE}/CodeSystem/AIdeviceTypeCS`;
export const AI_INPUTS_CS = `${AI_TRANSPARENCY_BASE}/CodeSystem/AIinputsCS`;

const TARGET_PATH_EXTENSION = 'http://hl7.org/fhir/StructureDefinition/targetPath';
const OBSERVATION_VALUE_CS = 'http://terminology.hl7.org/CodeSystem/v3-ObservationValue';
const AIAST_CODE = 'AIAST';
const PARTICIPANT_TYPE_CS = 'http://terminology.hl7.org/CodeSystem/provenance-participant-type';

/** AIinputsCS displays, for producers that send the code without one. */
const AI_INPUTS_DISPLAY: Record<string, string> = {
  AIModelCard: 'AI Model-Card',
  AIInputPrompt: 'AI Input Prompt',
  AIModelCardMarkdownFormat: 'Markdown format',
  AImodelCardCHAIformat: 'CHAI format'
};

/** Resource types that identify a Provenance agent as a person rather than a machine. */
const HUMAN_AGENT_TYPES = ['Practitioner', 'PractitionerRole', 'RelatedPerson', 'Patient', 'Person'];

/**
 * How much of the content the AI is responsible for, strongest first.
 * Derived from Provenance.agent.type for the AI agent(s).
 */
export type AiInvolvement = 'generated' | 'contributed' | 'reviewed' | 'asserted';

/** Whether a person signed off on the result, strongest first. */
export type HumanReview = 'verified' | 'involved' | 'none';

const AI_INVOLVEMENT_BY_PARTICIPANT_TYPE: Record<string, AiInvolvement> = {
  author: 'generated',
  composer: 'generated',
  assembler: 'contributed',
  enterer: 'contributed',
  informant: 'contributed',
  performer: 'contributed',
  source: 'contributed',
  custodian: 'contributed',
  transmitter: 'contributed',
  verifier: 'reviewed',
  attester: 'reviewed',
  legal: 'reviewed'
};

const HUMAN_REVIEW_BY_PARTICIPANT_TYPE: Record<string, HumanReview> = {
  verifier: 'verified',
  attester: 'verified',
  legal: 'verified'
};

const AI_INVOLVEMENT_RANK: Record<AiInvolvement, number> = {
  generated: 3,
  contributed: 2,
  reviewed: 1,
  asserted: 0
};

const HUMAN_REVIEW_RANK: Record<HumanReview, number> = { verified: 2, involved: 1, none: 0 };

const AI_INVOLVEMENT_LABEL: Record<AiInvolvement, string> = {
  generated: 'Generated by AI',
  contributed: 'AI contributed',
  reviewed: 'Reviewed by AI',
  asserted: 'Asserted by AI'
};

const AI_INVOLVEMENT_DETAIL: Record<AiInvolvement, string> = {
  generated: 'An AI system authored this content.',
  contributed: 'An AI system contributed to, but did not solely author, this content.',
  reviewed: 'An AI system reviewed or verified content authored elsewhere.',
  asserted: 'This content is labelled as artificial-intelligence asserted, without a recorded degree of involvement.'
};

const HUMAN_REVIEW_LABEL: Record<HumanReview, string> = {
  verified: 'Reviewed by a person',
  involved: 'A person took part',
  none: 'No human review recorded'
};

const HUMAN_REVIEW_DETAIL: Record<HumanReview, string> = {
  verified: 'A person verified or attested to this content after the AI system produced it.',
  involved: 'A person is recorded alongside the AI system, but not as a verifier or attester.',
  none: 'No person is recorded as having reviewed this content.'
};

export interface AiConfidence {
  /** Ready-to-render value, e.g. "95%", "moderate", "0.4 – 0.8". */
  display: string;
  /** Where the confidence was found; absent for the resource root. */
  path?: string;
}

export interface AiModelCard {
  /** Which of the IG's representations this Model-Card came from. */
  source: 'device-extension' | 'device-note' | 'provenance-entity';
  sourceLabel: string;
  title?: string;
  /** Model-Card format, e.g. "CHAI Format" or "Markdown Format". */
  format?: string;
  description?: string;
  /** Model-Card carried inline (Device.note.text, or a decoded text attachment). */
  text?: string;
  links: Array<{ url: string; contentType?: string }>;
}

export interface AiDeviceInfo {
  display: string;
  reference?: string;
  manufacturer?: string;
  modelNumber?: string;
  version?: string;
  url?: string;
  /** AIKind extension displays, e.g. "Large Language Models". */
  kinds: string[];
  modelCards: AiModelCard[];
}

export interface AiAgentInfo {
  /** Provenance.agent.type display, e.g. "Author". */
  typeLabel: string;
  /** Who the agent is: a device name, a practitioner reference, etc. */
  display: string;
}

export interface AiElementLabel {
  /** FHIRPath-ish location, e.g. "Procedure.followUp.text". */
  path: string;
  source: 'provenance-target-path' | 'element-confidence';
  confidence?: AiConfidence;
}

export interface AiProvenanceSummary {
  involvement: AiInvolvement;
  involvementLabel: string;
  involvementDetail: string;
  humanReview: HumanReview;
  humanReviewLabel: string;
  humanReviewDetail: string;
  /** True when the whole resource is labelled, false when only elements are. */
  resourceLevel: boolean;
  /** Plain-language reasons the resource as a whole is labelled. */
  resourceLevelSources: string[];
  /** Individually labelled elements; empty when labelling is resource-level only. */
  elementLevel: AiElementLabel[];
  /** Confidence recorded for the resource as a whole. */
  resourceConfidence?: AiConfidence;
  aiAgents: AiAgentInfo[];
  humanAgents: AiAgentInfo[];
  devices: AiDeviceInfo[];
  /** Provenance.activity text/displays. */
  activities: string[];
  /** Provenance.recorded, most recent first. */
  recorded: string[];
  /** Input prompts recorded as Provenance entities. */
  inputPrompts: Array<{ title?: string; description?: string; text?: string }>;
  /** Short label for the badge, e.g. "AI-generated". */
  badgeLabel: string;
}

export interface AiProvenanceIndex {
  /** AI Provenance resources keyed by every candidate key of their targets. */
  provenanceByTarget: Map<string, Provenance[]>;
  /** Every resource in scope, keyed by every candidate key it answers to. */
  resourcesByKey: Map<string, Resource>;
  /** False when nothing in scope carries AI labelling, so callers can skip work. */
  hasAny: boolean;
}

const EMPTY_INDEX: AiProvenanceIndex = {
  provenanceByTarget: new Map(),
  resourcesByKey: new Map(),
  hasAny: false
};

type IndexInput = Resource | BundleEntry | { resource?: Resource; fullUrl?: string } | undefined | null;

// --- reference/key plumbing -------------------------------------------------

/**
 * The keys a reference or resource answers to. References in the wild are
 * absolute ("http://ex.org/fhir/Observation/14"), relative ("Observation/14"),
 * or urn:uuid, and bundle fullUrls are often urn:uuid while the resource id is
 * the bare uuid; indexing every form lets those meet in the middle.
 */
function referenceKeys(reference: string | undefined): string[] {
  if (!reference) return [];
  const trimmed = reference.split('#')[0].split('?')[0].replace(/\/$/, '');
  if (!trimmed) return [];
  const keys = [trimmed];
  if (trimmed.startsWith('urn:')) {
    const id = trimmed.split(':').pop();
    if (id) keys.push(`id:${id}`);
    return keys;
  }
  const segments = trimmed.split('/');
  const id = segments[segments.length - 1];
  const type = segments[segments.length - 2];
  if (id) keys.push(`id:${id}`);
  if (id && type && /^[A-Z][A-Za-z]+$/.test(type)) keys.push(`${type}/${id}`);
  return keys;
}

function resourceKeys(resource: Resource, fullUrl?: string): string[] {
  const keys: string[] = [];
  if (resource.id) {
    keys.push(`id:${resource.id}`);
    keys.push(`${resource.resourceType}/${resource.id}`);
  }
  keys.push(...referenceKeys(fullUrl));
  return keys;
}

function normalizeInput(input: IndexInput): { resource?: Resource; fullUrl?: string } {
  if (!input) return {};
  if ('resourceType' in input && input.resourceType) return { resource: input as Resource };
  const entry = input as { resource?: Resource; fullUrl?: string };
  return { resource: entry.resource, fullUrl: entry.fullUrl };
}

// --- small FHIR helpers -----------------------------------------------------

function hasCoding(concept: CodeableConcept | undefined, system: string, code?: string): boolean {
  return !!concept?.coding?.some((c) => c.system === system && (code === undefined || c.code === code));
}

function conceptDisplay(concept: CodeableConcept | undefined): string | undefined {
  if (!concept) return undefined;
  if (concept.text) return concept.text;
  const coding = concept.coding?.find((c) => c.display || c.code);
  if (coding?.display) return coding.display;
  if (!coding?.code) return undefined;
  // The IG's own code systems use readable codes and producers routinely omit
  // the display, so show "Large Language Models", not the raw code.
  if (coding.system === AI_INPUTS_CS) return AI_INPUTS_DISPLAY[coding.code] ?? coding.code;
  if (coding.system === AI_DEVICE_TYPE_CS) return coding.code.replace(/-/g, ' ');
  return coding.code;
}

function extensionsOf(value: unknown): Extension[] {
  const extensions = (value as { extension?: Extension[] } | undefined)?.extension;
  return Array.isArray(extensions) ? extensions : [];
}

function isAiConfidenceExtension(extension: Extension): boolean {
  return extension.url === AI_CONFIDENCE_EXTENSION;
}

function confidenceFromExtension(extension: Extension, path?: string): AiConfidence | undefined {
  const ext = extension as Extension & { valueDecimal?: number; valueString?: string };
  if (typeof ext.valueDecimal === 'number') {
    return { display: `${Math.round(ext.valueDecimal * 100)}%`, path };
  }
  if (ext.valueQuantity) {
    const { value, unit, code } = ext.valueQuantity;
    const suffix = unit ?? code ?? '';
    if (value !== undefined) return { display: `${value}${suffix === '%' ? '%' : suffix ? ` ${suffix}` : ''}`, path };
  }
  if (ext.valueRange) {
    const low = ext.valueRange.low?.value;
    const high = ext.valueRange.high?.value;
    if (low !== undefined || high !== undefined) {
      return { display: `${low ?? '?'} – ${high ?? '?'}`, path };
    }
  }
  if (ext.valueCodeableConcept) {
    const display = conceptDisplay(ext.valueCodeableConcept);
    if (display) return { display, path };
  }
  if (ext.valueString) return { display: ext.valueString, path };
  return undefined;
}

export function isAiDevice(resource: Resource | undefined): resource is Device {
  if (!resource || resource.resourceType !== 'Device') return false;
  const device = resource as Device;
  if (device.meta?.profile?.includes(AI_DEVICE_PROFILE)) return true;
  if (hasCoding(device.type, AI_DEVICE_TYPE_CS)) return true;
  return extensionsOf(device).some((e) => e.url === AI_KIND_EXTENSION);
}

export function isModelCardDocument(resource: Resource | undefined): resource is DocumentReference {
  if (!resource || resource.resourceType !== 'DocumentReference') return false;
  const doc = resource as DocumentReference;
  return doc.meta?.profile?.includes(AI_MODEL_CARD_PROFILE) || hasCoding(doc.type, AI_INPUTS_CS, 'AIModelCard');
}

export function isInputPromptDocument(resource: Resource | undefined): resource is DocumentReference {
  if (!resource || resource.resourceType !== 'DocumentReference') return false;
  const doc = resource as DocumentReference;
  return doc.meta?.profile?.includes(AI_INPUT_PROMPT_PROFILE) || hasCoding(doc.type, AI_INPUTS_CS, 'AIInputPrompt');
}

function decodeTextAttachment(attachment: Attachment | undefined): string | undefined {
  if (!attachment?.data) return undefined;
  const contentType = attachment.contentType ?? '';
  if (!contentType.startsWith('text/') && contentType !== 'application/json') return undefined;
  try {
    // Browsers only; the callers of this module all run client-side.
    return decodeURIComponent(escape(atob(attachment.data)));
  } catch {
    return undefined;
  }
}

// --- index building ---------------------------------------------------------

/**
 * Index the AI Provenance resources in scope so a per-resource lookup is cheap.
 * Accepts raw resources or bundle entries; anything unrecognized is ignored.
 */
export function buildAiProvenanceIndex(input: IndexInput[] | undefined | null): AiProvenanceIndex {
  if (!input || input.length === 0) return EMPTY_INDEX;

  const resourcesByKey = new Map<string, Resource>();
  const provenances: Provenance[] = [];

  for (const item of input) {
    const { resource, fullUrl } = normalizeInput(item);
    if (!resource) continue;
    for (const key of resourceKeys(resource, fullUrl)) {
      if (!resourcesByKey.has(key)) resourcesByKey.set(key, resource);
    }
    if (resource.resourceType === 'Provenance') provenances.push(resource as Provenance);
  }

  const resolve = (reference: Reference | undefined, container?: Resource) =>
    resolveReference(reference, resourcesByKey, container);

  const provenanceByTarget = new Map<string, Provenance[]>();
  let hasAny = false;

  for (const provenance of provenances) {
    if (!isAiProvenance(provenance, resolve)) continue;
    hasAny = true;
    for (const target of provenance.target ?? []) {
      for (const key of referenceKeys(target.reference)) {
        const existing = provenanceByTarget.get(key);
        if (existing) {
          if (!existing.includes(provenance)) existing.push(provenance);
        } else {
          provenanceByTarget.set(key, [provenance]);
        }
      }
    }
  }

  if (!hasAny) {
    // A resource can be AI-labelled with no Provenance at all (meta.security or
    // an AIconfidence extension), so keep the index alive if any resource is.
    hasAny = input.some((item) => {
      const { resource } = normalizeInput(item);
      return !!resource && hasIntrinsicAiLabel(resource);
    });
  }

  return { provenanceByTarget, resourcesByKey, hasAny };
}

function resolveReference(
  reference: Reference | undefined,
  resourcesByKey: Map<string, Resource>,
  container?: Resource
): Resource | undefined {
  if (!reference?.reference) return undefined;
  const ref = reference.reference;
  if (ref.startsWith('#')) {
    const contained = (container as { contained?: Resource[] } | undefined)?.contained;
    return contained?.find((c) => c.id === ref.slice(1));
  }
  for (const key of referenceKeys(ref)) {
    const found = resourcesByKey.get(key);
    if (found) return found;
  }
  return undefined;
}

export type Resolver = (reference: Reference | undefined, container?: Resource) => Resource | undefined;

export function isAiProvenance(provenance: Provenance, resolve: Resolver): boolean {
  if (provenance.meta?.profile?.includes(AI_PROVENANCE_PROFILE)) return true;
  if (provenance.reason?.some((reason) => hasCoding(reason, OBSERVATION_VALUE_CS, AIAST_CODE))) return true;
  return (provenance.agent ?? []).some((agent) => isAiDevice(resolve(agent.who, provenance)));
}

/**
 * Whether a Provenance is worth resolving as AI provenance, judged from the
 * Provenance alone. Used at import time, before the agents' Devices have been
 * fetched: a conformant AI Provenance carries the profile or the AIAST reason,
 * and anything else with a Device agent is a maybe worth one read to settle.
 */
export function isAiProvenanceCandidate(provenance: Provenance): boolean {
  if (provenance.meta?.profile?.includes(AI_PROVENANCE_PROFILE)) return true;
  if (provenance.reason?.some((reason) => hasCoding(reason, OBSERVATION_VALUE_CS, AIAST_CODE))) return true;
  return (provenance.agent ?? []).some((agent) => agent.who?.reference?.includes('Device/'));
}

/**
 * Resources that exist only to describe AI involvement in *other* resources.
 * They are kept in the collection because the badge reads them, but they are
 * metadata rather than health data, so the resource lists leave them out.
 */
export function isAiTransparencySupportResource(resource: Resource | undefined): boolean {
  if (!resource) return false;
  switch (resource.resourceType) {
    case 'Provenance':
      return isAiProvenanceCandidate(resource as Provenance);
    case 'Device':
      return isAiDevice(resource);
    case 'DocumentReference':
      return isModelCardDocument(resource) || isInputPromptDocument(resource);
    case 'Binary':
      // Only ever pulled in as the body of a Model-Card attachment, and there is
      // no template that could render one.
      return true;
    default:
      return false;
  }
}

/**
 * AI labelling a resource carries on its own, with no Provenance involved. Runs
 * over every resource in scope, so it short-circuits rather than collecting.
 */
function hasIntrinsicAiLabel(resource: Resource): boolean {
  if (resource.meta?.security?.some((c) => c.system === OBSERVATION_VALUE_CS && c.code === AIAST_CODE)) return true;
  return containsAiConfidence(resource, 0);
}

function containsAiConfidence(node: unknown, depth: number): boolean {
  if (!node || typeof node !== 'object' || depth > 12) return false;
  if (Array.isArray(node)) return node.some((item) => containsAiConfidence(item, depth + 1));
  const record = node as Record<string, unknown>;
  if (extensionsOf(record).some(isAiConfidenceExtension)) return true;
  for (const [key, value] of Object.entries(record)) {
    if (key === 'extension' || key === 'modifierExtension' || key === 'contained' || key === 'text') continue;
    if (containsAiConfidence(value, depth + 1)) return true;
  }
  return false;
}

// --- element walking --------------------------------------------------------

interface FoundConfidence {
  /** Empty string for the resource root. */
  path: string;
  confidence: AiConfidence;
}

/**
 * Walk a resource looking for AIconfidence extensions, recording where each was
 * found so resource-level labels can be told apart from element-level ones.
 * `contained` is skipped: those are separate resources with their own labelling.
 */
function findConfidenceLabels(resource: Resource): FoundConfidence[] {
  const found: FoundConfidence[] = [];

  const visit = (node: unknown, path: string, depth: number) => {
    if (!node || typeof node !== 'object' || depth > 12) return;

    if (Array.isArray(node)) {
      node.forEach((item, index) => {
        visit(item, node.length > 1 ? `${path}[${index}]` : path, depth + 1);
      });
      return;
    }

    const record = node as Record<string, unknown>;
    for (const extension of extensionsOf(record)) {
      if (!isAiConfidenceExtension(extension)) continue;
      const confidence = confidenceFromExtension(extension, path || undefined);
      if (confidence) found.push({ path, confidence });
    }

    for (const [key, value] of Object.entries(record)) {
      if (key === 'extension' || key === 'modifierExtension' || key === 'contained' || key === 'text') continue;
      if (!value || typeof value !== 'object') continue;
      // A leading underscore carries the extensions of a primitive element,
      // e.g. followUp._text holds the extensions of followUp.text.
      const name = key.startsWith('_') ? key.slice(1) : key;
      visit(value, path ? `${path}.${name}` : name, depth + 1);
    }
  };

  visit(resource, '', 0);
  return found.map((f) => ({
    path: f.path ? `${resource.resourceType}.${f.path}` : '',
    confidence: f.path ? { ...f.confidence, path: `${resource.resourceType}.${f.path}` } : { ...f.confidence, path: undefined }
  }));
}

// --- model cards ------------------------------------------------------------

function modelCardFromDocument(
  doc: DocumentReference,
  source: AiModelCard['source'],
  sourceLabel: string,
  resolve: Resolver
): AiModelCard {
  const links: AiModelCard['links'] = [];
  let text: string | undefined;
  for (const content of doc.content ?? []) {
    const attachment = content.attachment;
    text = text ?? decodeTextAttachment(attachment);
    if (!attachment?.url) continue;
    // A Model-Card body can sit in a Binary rather than inline. Render it if we
    // hold it; a relative reference we cannot resolve would only be a dead link.
    const binary = resolve({ reference: attachment.url }, doc);
    if (binary?.resourceType === 'Binary') {
      text = text ?? decodeTextAttachment(binary as Attachment);
      continue;
    }
    if (/^https?:\/\//i.test(attachment.url)) {
      links.push({ url: attachment.url, contentType: attachment.contentType });
    }
  }
  return {
    source,
    sourceLabel,
    title: doc.identifier?.[0]?.value,
    format: doc.category?.map((c) => conceptDisplay(c)).find((d) => !!d),
    description: doc.description,
    text,
    links
  };
}

/** Identity of a Model-Card by its content, so the same card cited twice collapses. */
function modelCardKey(card: AiModelCard): string {
  return [card.title, card.format, card.description, card.text, card.links.map((l) => l.url).join(',')].join('|');
}

function modelCardsFromDevice(device: Device, resolve: Resolver): AiModelCard[] {
  const cards: AiModelCard[] = [];

  for (const extension of extensionsOf(device)) {
    if (extension.url !== MODEL_CARD_EXTENSION) continue;
    const resolved = resolve(extension.valueReference, device);
    if (isModelCardDocument(resolved)) {
      cards.push(modelCardFromDocument(resolved, 'device-extension', 'Attached to the AI Device', resolve));
    } else if (extension.valueReference?.display || extension.valueReference?.reference) {
      cards.push({
        source: 'device-extension',
        sourceLabel: 'Attached to the AI Device',
        title: extension.valueReference.display ?? extension.valueReference.reference,
        links: []
      });
    }
  }

  for (const note of (device.note ?? []) as Annotation[]) {
    if (!note.text) continue;
    cards.push({
      source: 'device-note',
      sourceLabel: 'Carried in Device.note',
      text: note.text,
      links: []
    });
  }

  return cards;
}

function deviceInfo(device: Device, reference: string | undefined, resolve: Resolver): AiDeviceInfo {
  const kinds = extensionsOf(device)
    .filter((e) => e.url === AI_KIND_EXTENSION)
    .map((e) => conceptDisplay(e.valueCodeableConcept))
    .filter((d): d is string => !!d);

  const name =
    device.deviceName?.find((n) => n.name)?.name ??
    device.modelNumber ??
    device.manufacturer ??
    conceptDisplay(device.type) ??
    reference ??
    'AI system';

  return {
    display: name,
    reference,
    manufacturer: device.manufacturer,
    modelNumber: device.modelNumber,
    version: device.version?.find((v) => v.value)?.value,
    url: device.url ?? device.contact?.find((c) => c.system === 'url')?.value,
    kinds,
    modelCards: modelCardsFromDevice(device, resolve)
  };
}

/**
 * An AI Device the resource itself points at, e.g. Observation.device. Only
 * references that resolve to an AI Device count, so ordinary medical devices
 * (an insulin pump on a DeviceUseStatement, say) never trigger AI labelling.
 */
function aiDeviceReferencedBy(
  resource: Resource,
  resolve: Resolver
): { device: Device; reference?: string } | undefined {
  const candidates: Reference[] = [];
  const collect = (value: unknown) => {
    if (!value || typeof value !== 'object') return;
    if (Array.isArray(value)) {
      value.forEach(collect);
      return;
    }
    const reference = value as Reference;
    if (typeof reference.reference === 'string') candidates.push(reference);
  };
  for (const [key, value] of Object.entries(resource as unknown as Record<string, unknown>)) {
    if (key === 'contained' || key === 'meta' || key === 'extension') continue;
    collect(value);
  }
  for (const reference of candidates) {
    const resolved = resolve(reference, resource);
    if (isAiDevice(resolved)) return { device: resolved, reference: reference.reference };
  }
  return undefined;
}

// --- the per-resource summary ----------------------------------------------

/**
 * The AI provenance to show for one resource, or undefined when it carries none
 * — in which case the caller renders nothing at all.
 */
export function getAiProvenance(
  resource: Resource | undefined,
  index: AiProvenanceIndex | undefined
): AiProvenanceSummary | undefined {
  if (!resource) return undefined;
  const idx = index ?? EMPTY_INDEX;
  const resolve: Resolver = (reference, container) => resolveReference(reference, idx.resourcesByKey, container);

  const provenances = provenancesFor(resource, idx);
  const securityLabelled = !!resource.meta?.security?.some(
    (c) => c.system === OBSERVATION_VALUE_CS && c.code === AIAST_CODE
  );
  const confidences = findConfidenceLabels(resource);
  const referencedDevice = aiDeviceReferencedBy(resource, resolve);

  if (provenances.length === 0 && !securityLabelled && confidences.length === 0 && !referencedDevice) {
    return undefined;
  }

  const resourceLevelSources: string[] = [];
  let resourceLevel = false;
  const elementLevel: AiElementLabel[] = [];

  if (securityLabelled) {
    resourceLevel = true;
    resourceLevelSources.push('The resource carries the "Artificial Intelligence asserted" security label.');
  }

  const seenPaths = new Set<string>();
  for (const provenance of provenances) {
    const targets = (provenance.target ?? []).filter((target) =>
      referenceKeys(target.reference).some((key) => resourceMatchesKey(resource, key))
    );
    for (const target of targets) {
      const targetPaths = extensionsOf(target)
        .filter((e) => e.url === TARGET_PATH_EXTENSION)
        .map((e) => e.valueString)
        .filter((p): p is string => !!p);
      if (targetPaths.length === 0) {
        resourceLevel = true;
        resourceLevelSources.push('An AI Provenance records this whole resource as its target.');
      }
      for (const path of targetPaths) {
        if (seenPaths.has(path)) continue;
        seenPaths.add(path);
        elementLevel.push({ path, source: 'provenance-target-path' });
      }
    }
  }

  let resourceConfidence: AiConfidence | undefined;
  for (const found of confidences) {
    if (!found.path) {
      resourceConfidence = found.confidence;
      resourceLevel = true;
      resourceLevelSources.push('An AI confidence is recorded for the resource as a whole.');
      continue;
    }
    const existing = elementLevel.find((e) => e.path === found.path);
    if (existing) {
      existing.confidence = found.confidence;
    } else {
      seenPaths.add(found.path);
      elementLevel.push({ path: found.path, source: 'element-confidence', confidence: found.confidence });
    }
  }

  if (referencedDevice && !resourceLevel && elementLevel.length === 0) {
    resourceLevel = true;
    resourceLevelSources.push('The resource names an AI Device as its source.');
  }

  // Agents, degree of involvement, and human review.
  const aiAgents: AiAgentInfo[] = [];
  const humanAgents: AiAgentInfo[] = [];
  const devices: AiDeviceInfo[] = [];
  const seenDeviceKeys = new Set<string>();
  let involvement: AiInvolvement = 'asserted';
  let humanReview: HumanReview = 'none';

  const addDevice = (device: Device, reference?: string) => {
    const key = reference ?? device.id ?? device.manufacturer ?? String(devices.length);
    if (seenDeviceKeys.has(key)) return;
    seenDeviceKeys.add(key);
    devices.push(deviceInfo(device, reference, resolve));
  };

  if (referencedDevice) addDevice(referencedDevice.device, referencedDevice.reference);

  const activities: string[] = [];
  const recorded: string[] = [];
  const inputPrompts: AiProvenanceSummary['inputPrompts'] = [];
  const provenanceModelCards: AiModelCard[] = [];

  for (const provenance of provenances) {
    const activity = conceptDisplay(provenance.activity);
    if (activity && !activities.includes(activity)) activities.push(activity);
    if (provenance.recorded && !recorded.includes(provenance.recorded)) recorded.push(provenance.recorded);

    for (const agent of provenance.agent ?? []) {
      const who = resolve(agent.who, provenance);
      const typeCode = agent.type?.coding?.find((c) => c.system === PARTICIPANT_TYPE_CS)?.code;
      const typeLabel = conceptDisplay(agent.type) ?? typeCode ?? 'Participant';
      if (isAiDevice(who)) {
        addDevice(who, agent.who?.reference);
        aiAgents.push({ typeLabel, display: agentDisplay(agent, who) });
        const mapped = typeCode ? AI_INVOLVEMENT_BY_PARTICIPANT_TYPE[typeCode] : undefined;
        if (mapped && AI_INVOLVEMENT_RANK[mapped] > AI_INVOLVEMENT_RANK[involvement]) involvement = mapped;
      } else if (isHumanAgent(agent, who)) {
        humanAgents.push({ typeLabel, display: agentDisplay(agent, who) });
        const mapped = (typeCode ? HUMAN_REVIEW_BY_PARTICIPANT_TYPE[typeCode] : undefined) ?? 'involved';
        if (HUMAN_REVIEW_RANK[mapped] > HUMAN_REVIEW_RANK[humanReview]) humanReview = mapped;
      }
    }

    for (const entity of provenance.entity ?? []) {
      const what = resolve(entity.what, provenance);
      if (isModelCardDocument(what)) {
        provenanceModelCards.push(modelCardFromDocument(what, 'provenance-entity', 'Referenced by the AI Provenance', resolve));
      } else if (isInputPromptDocument(what)) {
        const doc = what as DocumentReference;
        inputPrompts.push({
          title: doc.identifier?.[0]?.value,
          description: doc.description,
          text: doc.content?.map((c) => decodeTextAttachment(c.attachment)).find((t) => !!t)
        });
      }
    }
  }

  // Model-Cards found via the Provenance belong with the device they describe
  // when there is exactly one; otherwise they stand on their own. A producer
  // that both attaches the card to the Device and cites it from the Provenance
  // should not make the reader read it twice.
  if (provenanceModelCards.length > 0) {
    if (devices.length === 1) {
      const seen = new Set(devices[0].modelCards.map(modelCardKey));
      for (const card of provenanceModelCards) {
        if (seen.has(modelCardKey(card))) continue;
        seen.add(modelCardKey(card));
        devices[0].modelCards.push(card);
      }
    } else {
      devices.push({ display: 'AI system', kinds: [], modelCards: provenanceModelCards });
    }
  }

  const badgeLabel =
    involvement === 'generated'
      ? 'AI-generated'
      : involvement === 'contributed'
        ? 'AI-assisted'
        : involvement === 'reviewed'
          ? 'AI-reviewed'
          : 'AI-asserted';

  return {
    involvement,
    involvementLabel: AI_INVOLVEMENT_LABEL[involvement],
    involvementDetail: AI_INVOLVEMENT_DETAIL[involvement],
    humanReview,
    humanReviewLabel: HUMAN_REVIEW_LABEL[humanReview],
    humanReviewDetail: HUMAN_REVIEW_DETAIL[humanReview],
    resourceLevel,
    resourceLevelSources: Array.from(new Set(resourceLevelSources)),
    elementLevel,
    resourceConfidence,
    aiAgents,
    humanAgents,
    devices,
    activities,
    recorded: recorded.sort().reverse(),
    inputPrompts,
    badgeLabel
  };
}

function provenancesFor(resource: Resource, index: AiProvenanceIndex): Provenance[] {
  const found: Provenance[] = [];
  for (const key of resourceKeys(resource)) {
    for (const provenance of index.provenanceByTarget.get(key) ?? []) {
      if (!found.includes(provenance)) found.push(provenance);
    }
  }
  return found;
}

function resourceMatchesKey(resource: Resource, key: string): boolean {
  return resourceKeys(resource).includes(key);
}

function isHumanAgent(agent: ProvenanceAgent, who: Resource | undefined): boolean {
  if (who) return HUMAN_AGENT_TYPES.includes(who.resourceType);
  const reference = agent.who?.reference ?? '';
  return HUMAN_AGENT_TYPES.some((type) => reference.includes(`${type}/`));
}

function agentDisplay(agent: ProvenanceAgent, who: Resource | undefined): string {
  if (agent.who?.display) return agent.who.display;
  if (who?.resourceType === 'Device') {
    const device = who as Device;
    return device.deviceName?.find((n) => n.name)?.name ?? device.manufacturer ?? 'AI system';
  }
  if (who && 'name' in who) {
    const name = (who as { name?: unknown }).name;
    if (typeof name === 'string') return name;
    if (Array.isArray(name)) {
      const first = name[0] as { text?: string; given?: string[]; family?: string } | undefined;
      if (first?.text) return first.text;
      if (first) return [first.given?.join(' '), first.family].filter(Boolean).join(' ') || 'Unnamed';
    }
  }
  return agent.who?.reference ?? 'Unknown participant';
}
