FROM node:24

ARG VITE_APP_VERSION_STRING
ENV VITE_APP_VERSION_STRING=$VITE_APP_VERSION_STRING

WORKDIR /opt/app

# Only install dependencies
COPY package*.json ./
RUN npm clean-install

EXPOSE 3000

CMD ["npm", "run", "dev"]