<script lang="ts">
  import { writable } from 'svelte/store';
  import { page } from "$app/stores";
  import {
    Col,
    Dropdown,
    DropdownItem,
    DropdownMenu,
    DropdownToggle,
    Icon,
    TabContent,
    TabPane,
    Row,
  } from 'sveltestrap';
  import * as shlClient from '$lib/utils/shlClient';
  import { verify } from '$lib/utils/shcDecoder.js';
  import type { Bundle, Composition, Patient } from 'fhir/r4';
  
  import IPSContent from '$lib/components/viewer/IPSContent.svelte';
  import Demo from '$lib/components/viewer/Demo.svelte';
  
  import { SHOW_VIEWER_DEMO } from "$lib/config/config";
  import { INSTANCE_CONFIG } from '$lib/config/instance_config';

  let shlContents: Bundle[] = [];

  let loading: boolean;
  const shl = $page.url.hash.match(/shlink:\/.*/)?.[0];
  $: {
    if (shl) {
      try {
        loading = true;
        retrieve().then(() => loading = false);
      } catch (e) {
        console.error(e);
        setError("There was a problem loading this SMART Health Link. Please ensure the link is active before trying again.");
      }
    }
  }

  // Display mode logic
  interface DisplayMode {
    buttonText: string;
    dropdownText: string;
  }
  let displayMode = writable("app");
  let displayModes:Record<string, DisplayMode> = {
    app: {
      buttonText: "App Interpretation",
      dropdownText: "Display app's interpretation of resources"
    },
    text: {
      buttonText: "Generated Text",
      dropdownText: "Display text generated by IPS source"
    }
  }

  let displayModeText:string;
  $: {
    if ($displayMode) {
      displayModeText = displayModes[$displayMode].buttonText;
    }
  }

  function setMode(mode:string) {
    $displayMode = mode;
  }
  // End display mode logic

  // Status display logic
  let status = "Retrieving contents...";
  let showStatus = true;

  $: {
    if (shlContents.length > 0) {
      setStatus("");
    }
  }
  function setStatus(message:string) {
    status = message;
    showStatus = message !== "";
  }
  // End status display logic

  // Error display and handling logic
  let showError = false;
  let errorMessage = "";

  function setError(message:string) {
    errorMessage = message;
    showError = message !== "";
  }
  // End error display and handling logic

  // Retrieving SHL
  async function retrieve(){
    const recipient = `${INSTANCE_CONFIG.title} Viewer`;

    let retrieveResult;
    let passcode;
    try {
        retrieveResult = await fetch(shlClient.url({ shl: shl ?? "" }), {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
          },
          body: JSON.stringify({
            recipient: recipient,
          }),
        });
      let message = await retrieveResult.text();
      message = JSON.parse(message)?.message;
      if (!retrieveResult.ok && retrieveResult.status === 401 && message === "Passcode required") {
        // Failed the password requirement
        const needPasscode = shlClient.flag({ shl: shl ?? "" })?.includes('P');
        if (needPasscode) {
          passcode = prompt(`${INSTANCE_CONFIG.title} Viewer\n----------------------------------------\nEnter a passcode to access this SMART Health Link`);
        }
      }
    } catch (e) {
      let message = "Error retrieving SMART Health Link Manifest";
      console.log(`${message}: ${e}`);
      setError(message);
      return;
    }
    
    try {
      retrieveResult = await shlClient.retrieve({
          shl: shl ?? "",
          passcode: passcode ?? "",
          recipient
      });
    } catch (e) {
      console.log(e);
      setError(e.message);
      return;
    }

    if (retrieveResult === undefined) {
      setError("Unable to retrieve SMART Health Link.");
      return;
    }
 
    if (retrieveResult.error) {
        let errorMsg = "";
        if (retrieveResult.status) {
            if (retrieveResult.status === 404) {
                // Couldn't find the shl, or it's been deactivated
                const managerLink = `<a href="${new URL(import.meta.url).origin}/view/${shlClient.id({ shl: shl ?? "" })}">Manage or reactivate it here</a>`;
                errorMsg = `<p>This SMART Health Link does not exist or has been deactivated.</p><p>Are you the owner of this link? ${managerLink}</p>`;
            } else if (retrieveResult.status === 401) {
                // Failed the password requirement
                while (retrieveResult.status === 401) {
                  passcode = prompt(`${INSTANCE_CONFIG.title} Viewer\n----------------------------------------\nIncorrect passcode.\nEnter a passcode to access this SMART Health Link`);
                    try {
                        retrieveResult = await shlClient.retrieve({
                            shl: shl ?? "",
                            passcode: passcode ?? "",
                            recipient
                        });
                    } catch (e) {
                        // Retrieval succeeded, but there was an error parsing files etc.
                        console.log(e);
                        throw Error("Content parsing error");
                    }
                }
                if (retrieveResult.error) {
                    const managerLink = `<a href="${new URL(import.meta.url).origin}/view/${shlClient.id({ shl: shl ?? "" })}">Manage or reactivate it here</a>`;
                    errorMsg = `<p>You have been locked from accessing this SMART Health Link due to too many failed password attempts.</p><p>Are you the owner of this link? ${managerLink}</p>`;
                }
            } else {
                errorMsg = retrieveResult.error;
            }
        }
        if (errorMsg !== "") {
          setError(errorMsg);
          return;
        }
    }
    if (retrieveResult.shcs) {
      const decoded = await Promise.all(retrieveResult.shcs.map(verify));
      const data = decoded.map((e) => e.fhirBundle);
      shlContents = data;
    }
    if (retrieveResult.jsons) {
      shlContents = [...shlContents, ...retrieveResult.jsons];
    }
}
  // End retrieving SHL

  function getTabLabel(ipsContent: Bundle) {
    let tabName = "";
    let date = "";
    let name = "";

    if (ipsContent.entry) {
      for (const entry of ipsContent.entry) {
        if (entry.resource?.resourceType === "Patient") {
          const patient = entry.resource as Patient;
          if (patient.name?.[0].given?.[0]) {
            name = patient.name?.[0].given?.[0];
          }
          break;
        }
      }
      const composition = ipsContent.entry[0].resource as Composition;
      if (composition.date) {
        date = `(${composition.date.split('T')[0]})`;
      }
    }
    tabName = name ? `${name}'s Summary` : 'Your Summary';

    if (date) {
      tabName += ` ${date}`;
    }

    return tabName;
  }
  
</script>

<Row class="d-flex justify-content-start mx-0 pb-4">
  <Col class="d-flex justify-content-start align-items-center">
    Displaying FHIR Resources Using:
    <Dropdown style="margin-left: 10px">
      <DropdownToggle color="secondary" caret>
        {displayModeText}
      </DropdownToggle>
      <DropdownMenu>
        {#each Object.entries(displayModes) as [mode, {buttonText, dropdownText}]}
          <DropdownItem
            on:click={() => {
              setMode(mode);
          }}>
            <Row class="mr-0" style="min-width:340px">
              <Col class="d-flex justify-content-start align-items-center pe-0">
                {dropdownText}
              </Col>
              <Col class="d-flex justify-content-end ps-0">
                {#if mode === $displayMode} <Icon name="check" class="text-success fs-5"/>{/if}
              </Col>
            </Row>
          </DropdownItem>
        {/each}
      </DropdownMenu>
    </Dropdown>
  </Col>
</Row>
{#if showError}
  <Row class="text-danger">
    {@html errorMessage}
  </Row>
{:else if loading}
  <Row id="ips-loader" class="mx-2">
    <Row>
      {@html status}
    </Row>
    <span class="loader"></span>
  </Row>
{:else if shlContents.length > 1 || SHOW_VIEWER_DEMO}
  <!-- Multiple tab/demo view -->
  <TabContent>
    {#each shlContents as contents, index}
      <TabPane class={`ips${index}`} tabId={`ips${index}`} active={index === 0} style="padding-top:10px">
        <span slot="tab">{getTabLabel(contents)}</span>
        <IPSContent bundle={contents} mode={$displayMode} />
      </TabPane>
    {/each}
    {#if SHOW_VIEWER_DEMO}
      <TabPane tabId="demo" active={shlContents.length === 0} style="padding-top:10px">
        <span class="demo-tab" slot="tab">IPS Sandbox</span>
        <Demo bundle={shlContents[0]} mode={$displayMode} />
      </TabPane>
    {/if}
  </TabContent>
{:else}
  <!-- Single tab view -->
  <IPSContent bundle={shlContents[0]} mode={$displayMode} />
{/if}
