<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import { writable, type Readable } from 'svelte/store';
  import { slide } from 'svelte/transition';
  import { page } from "$app/stores";
  import type { User } from 'oidc-client-ts';
  import type { IAuthService } from '$lib/utils/types';
  import {
    Button,
    Col,
    Dropdown,
    DropdownItem,
    DropdownMenu,
    DropdownToggle,
    Form,
    FormGroup,
    Icon,
    Input,
    Label,
    Modal,
    ModalBody,
    ModalFooter,
    ModalHeader,
    TabContent,
    TabPane,
    Row,
  } from '@sveltestrap/sveltestrap';
  import * as shlClient from '$lib/utils/shlClient';
  import { verify } from '$lib/utils/shcDecoder.js';
  import type { Bundle, Composition, Patient } from 'fhir/r4';
  
  import IPSContent from '$lib/components/viewer/IPSContent.svelte';
  import Demo from '$lib/components/viewer/Demo.svelte';
  import ImmunizationDecisionSupport from '$lib/components/app/ImmunizationDecisionSupport.svelte';
  
  import { SHOW_VIEWER_DEMO } from "$lib/config/config";
  import { INSTANCE_CONFIG } from '$lib/config/instance_config';

  let shlContents: Bundle[] = [];

  const shl = $page.url.hash.match(/shlink:\/.*/)?.[0];

  const authService: IAuthService = getContext('authService');
  const user: Readable<User | null> = authService.user;

  let loading = !!shl;
  let loaded = !shl;

  // Access dialogue state
  let modalOpen = false;
  let recipientInput = "";
  let passcode = "";
  let showPasscode = false;
  let passcodeIncorrect = false;
  let incorrectFeedback = "";
  let feedback = "Incorrect passcode.";
  let submitting = false;
  let authenticated = false;
  let authedRecipient = "";

  function getUserDisplayName(profile: User['profile'] | undefined): string {
    if (!profile) return "";
    const full = [profile.given_name, profile.family_name].filter(Boolean).join(" ");
    return (profile.name as string) || full || (profile.preferred_username as string) || (profile.email as string) || "";
  }

  onMount(async () => {
    if (!shl) {
      loading = false;
      return;
    }
    try {
      authenticated = !!(await authService.isAuthenticated());
    } catch (e) {
      authenticated = false;
    }
    authedRecipient = authenticated ? getUserDisplayName($user?.profile) : "";
    if (authedRecipient) {
      await attempt();
    } else {
      // Need a self-attested recipient name before the first request
      authenticated = false;
      loading = false;
      modalOpen = true;
    }
  });

  $: recipient = authedRecipient || recipientInput.trim();
  $: canSubmit = !!recipient && (!showPasscode || passcode !== "") && !submitting;

  // Display mode logic
  interface DisplayMode {
    buttonText: string;
    dropdownText: string;
  }
  let displayMode = writable("app");
  let displayModes:Record<string, DisplayMode> = {
    app: {
      buttonText: "App Interpretation",
      dropdownText: "Display app's interpretation of resources"
    },
    text: {
      buttonText: "Generated Text",
      dropdownText: "Display text generated by IPS source"
    }
  }

  let displayModeText:string;
  $: {
    if ($displayMode) {
      displayModeText = displayModes[$displayMode].buttonText;
    }
  }

  function setMode(mode:string) {
    $displayMode = mode;
  }
  // End display mode logic

  // Status display logic
  let status = "Retrieving contents...";
  let showStatus = true;

  $: {
    if (shlContents.length > 0) {
      setStatus("");
    }
  }
  function setStatus(message:string) {
    status = message;
    showStatus = message !== "";
  }
  // End status display logic

  // Error display and handling logic
  let showError = false;
  let errorMessage = "";

  function setError(message:string) {
    errorMessage = message;
    showError = message !== "";
  }
  // End error display and handling logic

  // Retrieving SHL
  async function attempt() {
    submitting = true;
    if (!modalOpen) loading = true;
    try {
      await retrieve();
    } finally {
      submitting = false;
      loading = false;
    }
  }

  async function retrieve() {
    let retrieveResult;
    try {
      retrieveResult = await shlClient.retrieve({
        shl: shl ?? "",
        passcode: passcode ?? "",
        recipient
      });
    } catch (e) {
      console.log(e);
      modalOpen = false;
      setError(e.message);
      return;
    }

    if (retrieveResult === undefined) {
      modalOpen = false;
      setError("Unable to retrieve SMART Health Link.");
      return;
    }

    if (retrieveResult.error) {
      const managerLink = `<a href="${new URL(import.meta.url).origin}/view/${shlClient.id({ shl: shl ?? "" })}">Manage or reactivate it here</a>`;
      const needPasscode = shlClient.flag({ shl: shl ?? "" })?.includes('P');
      if (retrieveResult.status === 401 || (retrieveResult.status === 400 && needPasscode)) {
        // Passcode missing or incorrect: ask for it in the dialogue
        passcodeIncorrect = showPasscode && passcode !== "";
        const attempts = retrieveResult.error.details?.remainingAttempts;
        let attemptsMsg = "";
        if (attempts && attempts <= 3) {
          attemptsMsg = ` You have ${attempts} attempt${attempts === 1 ? "" : "s"} remaining.`;
        }
        incorrectFeedback = `${feedback}${attemptsMsg}`;
        passcode = "";
        showPasscode = true;
        modalOpen = true;
        return;
      }
      modalOpen = false;
      if (retrieveResult.status === 404) {
        // Couldn't find the shl, or it's been deactivated
        setError(`<p>This SMART Health Link does not exist or has been deactivated.</p><p>Are you the owner of this link? ${managerLink}</p>`);
      } else if (retrieveResult.status === 403) {
        const lockout = retrieveResult.error.details?.retryAfterSeconds;
        let lockoutMsg = "";
        if (lockout) {
            const minutes = Math.ceil(lockout / 60);
            const hours = Math.floor(minutes / 60);
            const amt = hours >= 1 ? `${hours} hour${hours === 1 ? "" : "s"}` : `${minutes} minute${minutes === 1 ? "" : "s"}`;
            lockoutMsg = ` You may try again in ${amt}.`;
        }
        const managerLink = `<a href="${new URL(import.meta.url).origin}/view/${shlClient.id({ shl: shl ?? "" })}">Log in to view it here</a>`;
        setError(`<p>You have been locked from accessing this SMART Health Link from this device due to too many failed password attempts.${lockoutMsg}</p><p>Are you the owner of this link? ${managerLink}</p>`);
      } else if (retrieveResult.status === 429) {
        setError(`<p>Unable to retrieve SMART Health Link due to too many requests. Please wait before trying again.</p>`);
      } else if (showPasscode) {
        setError(`<p>You have been locked from accessing this SMART Health Link due to too many failed password attempts.</p><p>Are you the owner of this link? ${managerLink}</p>`);
      } else {
        setError(typeof retrieveResult.error === "string" ? retrieveResult.error : "Unable to retrieve SMART Health Link.");
      }
      return;
    }

    try {
      if (retrieveResult.shcs) {
        const decoded = await Promise.all(retrieveResult.shcs.map(verify));
        shlContents = decoded.map((e) => e.fhirBundle);
      }
      if (retrieveResult.jsons) {
        shlContents = [...shlContents, ...retrieveResult.jsons];
      }
    } catch (e) {
      console.log(e);
      modalOpen = false;
      setError("Content parsing error");
      return;
    }
    modalOpen = false;
    loaded = true;
  }

  function onSubmit(event: Event) {
    event.preventDefault();
    if (canSubmit) attempt();
  }
  // End retrieving SHL

  function getTabLabel(ipsContent: Bundle) {
    let tabName = "";
    let date = "";
    let name = "";

    if (ipsContent.entry) {
      for (const entry of ipsContent.entry) {
        if (entry.resource?.resourceType === "Patient") {
          const patient = entry.resource as Patient;
          if (patient.name?.[0].given?.[0]) {
            name = patient.name?.[0].given?.[0];
          }
          break;
        }
      }
      const composition = ipsContent.entry[0].resource as Composition;
      if (composition.date) {
        date = `(${composition.date.split('T')[0]})`;
      }
    }
    tabName = name ? `${name}'s Summary` : 'Your Summary';

    if (date) {
      tabName += ` ${date}`;
    }

    return tabName;
  }
  
  let decisionSupportContent = shlContents[0];
</script>

<Modal isOpen={modalOpen} backdrop="static" keyboard={false} centered>
  <Form on:submit={onSubmit}>
    <ModalHeader>{INSTANCE_CONFIG.title} Viewer</ModalHeader>
    <ModalBody>
      {#if !authenticated}
        <FormGroup>
          <Label for="recipient">Who are you?</Label>
          <Input
            id="recipient"
            type="text"
            placeholder="Your name or organization"
            bind:value={recipientInput}
            disabled={showPasscode && submitting} />
        </FormGroup>
      {/if}
      {#if showPasscode}
        <div transition:slide>
          <FormGroup>
            <Label for="passcode">Enter a passcode to access this SMART Health Link</Label>
            <Input
              id="passcode"
              type="password"
              bind:value={passcode}
              invalid={passcodeIncorrect}
              feedback={incorrectFeedback}
              autofocus />
          </FormGroup>
        </div>
      {/if}
    </ModalBody>
    <ModalFooter>
      <Button type="submit" color="primary" disabled={!canSubmit}>
        {submitting ? "Retrieving..." : "Continue"}
      </Button>
    </ModalFooter>
  </Form>
</Modal>

{#if loaded || showError}
<Row class="d-flex justify-content-start mx-0 pb-4">
  <Col class="d-flex justify-content-start align-items-center">
    Displaying FHIR Resources Using:
    <Dropdown style="margin-left: 10px">
      <DropdownToggle color="secondary" caret>
        {displayModeText}
      </DropdownToggle>
      <DropdownMenu>
        {#each Object.entries(displayModes) as [mode, {buttonText, dropdownText}]}
          <DropdownItem
            on:click={() => {
              setMode(mode);
          }}>
            <Row class="mr-0" style="min-width:340px">
              <Col class="d-flex justify-content-start align-items-center pe-0">
                {dropdownText}
              </Col>
              <Col class="d-flex justify-content-end ps-0">
                {#if mode === $displayMode} <Icon name="check" class="text-success fs-5"/>{/if}
              </Col>
            </Row>
          </DropdownItem>
        {/each}
      </DropdownMenu>
    </Dropdown>
  </Col>
</Row>
{#if showError}
  <Row class="text-danger">
    {@html errorMessage}
  </Row>
{:else if shlContents.length > 1 || SHOW_VIEWER_DEMO}
  <!-- Multiple tab/demo view -->
  <TabContent>
    {#if shlContents.length > 0}
      {#each shlContents as contents, index}
        <TabPane class={`ips${index}`} tabId={`ips${index}`} active={index === 0} style="padding-top:10px">
          <span slot="tab">{getTabLabel(contents)}</span>
          <IPSContent bundle={contents} mode={$displayMode} />
        </TabPane>
      {/each}
      <TabPane class="decision-support-tab" tabId="decision-support" style="padding-top:10px">
        <span class="decision-support-tab" slot="tab">Decision Support</span>
        <Row>
          <Col>
            <p>Get recommendations and health record analysis based the health summary content.</p>
            {#if shlContents.length > 1}
              <Label>Select a summary to use for decision support:</Label>
              <select bind:value={decisionSupportContent}>
                {#each shlContents as content}
                  <option value={content}>{getTabLabel(content)}</option>
                {/each}
              </select>
            {/if}
          </Col>
        </Row>
        <ImmunizationDecisionSupport
          patient={shlContents[0].entry.find(entry => entry.resource.resourceType === "Patient").resource}
          immunizations={shlContents[0].entry.filter(entry => entry.resource.resourceType === "Immunization").map(entry => entry.resource)} />
      </TabPane>
    {/if}
    {#if SHOW_VIEWER_DEMO}
      <TabPane tabId="demo" active={shlContents.length === 0} style="padding-top:10px">
        <span class="demo-tab" slot="tab">IPS Sandbox</span>
        <Demo bundle={shlContents[0]} mode={$displayMode} />
      </TabPane>
    {/if}
  </TabContent>
{:else}
  <!-- Single tab view -->
  <IPSContent bundle={shlContents[0]} mode={$displayMode} />
{/if}
{:else if loading}
  <Row id="ips-loader" class="mx-2">
    <Row>
      {@html status}
    </Row>
    <span class="loader"></span>
  </Row>
{/if}
