# run the test suite in the "test" Docker stage on every push
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git commit
        uses: actions/checkout@main

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: test
          load: true
          tags: shl-ips-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: docker run --rm shl-ips-test:latest
